// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'hd': string;
  'item': string;
  'tab_current_item': string;
  'tab_item': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
