// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'container': string;
  'desc': string;
  'icon': string;
  'item': string;
  'left': string;
  'left_inner': string;
  'link': string;
  'liq_item': string;
  'main_title': string;
  'name': string;
  'no_data': string;
  'no_data_title': string;
  'right': string;
  'sidebar': string;
  'strong': string;
  'subtitle': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
