// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'current_trigger': string;
  'trigger': string;
  'trigger_wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
