// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amount': string;
  'btn': string;
  'btns': string;
  'cancel': string;
  'icon': string;
  'item': string;
  'label': string;
  'pay_container': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
