'use strict';
import React, { Component } from 'react';
import Chart from 'components/chart';
import Transactions from 'components/transactions';
import styles from './index.less';
import _ from 'i18n';

import HeadLeft from '../layout/head/headLeft';
import HeadRight from '../layout/head/headRight';
import Swap from '../swap';
import PairStat from '../pairStat';

export default class SwapPage extends Component {
    constructor(props) {
        super(props);
        this.state = {

        }
    }

    renderContent() {

        return <div className={styles.content}>
            <div className={styles.main_title}>
                <h2><span className={styles.strong}>BSV</span>/vUSD</h2>
                <div className={styles.subtitle}><span className={styles.strong}>255.55</span> vUSD {_('per')} BSV </div>
            </div>
            <Chart />
            <h3 className={styles.title}>{_('about')} Bitcoin SV</h3>
            <div className={styles.p}>
                <p className={styles.desc}>Bitcoin Satoshi Vision (SV) is a cryptocurrency created in late 2018 by adjusting the protocol with larger block sizes to reduce transaction fees. The name comes from its supporters belief that cheaper fees aligns with Satoshi Nakamoto's vision for Bitcoin.</p>
                <div className={styles.link}><a href='' target='_blank'>{_('website')}</a></div>
            </div>
            <h3 className={styles.title}>{_('about')} vUSD</h3>
            <div className={styles.p}>
                <p className={styles.desc}>vUSD is a stable coin token based on BSV blockchain backed by USDC and DAI stable coin. vUSD liquidity providers get 10% of fees generated by TokenSwap traders.</p>
                <div className={styles.link}><a href='' target='_blank'>{_('website')}</a></div>
            </div>
            <h3 className={styles.title}>BSV/vUSD {_('transactions')}</h3>
            <Transactions />
            <h3 className={styles.title}>{_('pair_stat')}</h3>
            <PairStat />
        </div>;
    }

    render() {
        return (<section className={styles.container}>
            <section className={styles.left}>
                <div className={styles.left_inner}>
                    <HeadLeft />
                    {this.renderContent()}
                </div>
            </section>
            <section className={styles.right}>
                <div className={styles.sidebar}>
                    <HeadRight />
                    <Swap />
                </div>
            </section>
        </section>)
    }
}