// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abs_item': string;
  'abstract': string;
  'btn': string;
  'btns': string;
  'col_1': string;
  'col_2': string;
  'col_3': string;
  'content': string;
  'green': string;
  'head': string;
  'head_inner': string;
  'head_right': string;
  'label': string;
  'list': string;
  'list_hd': string;
  'list_item': string;
  'logo': string;
  'main': string;
  'main_desc': string;
  'main_title': string;
  'red': string;
  'title': string;
  'title_h5': string;
  'title_web': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
