// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acc_list': string;
  'acc_list_box': string;
  'account': string;
  'account_icon': string;
  'account_name': string;
  'account_trigger': string;
  'app_title': string;
  'btn': string;
  'btns': string;
  'cancel': string;
  'connect': string;
  'connect_app': string;
  'dia_title': string;
  'dialog': string;
  'ft': string;
  'hd': string;
  'line': string;
  'login_dialog': string;
  'persission_title': string;
  'tips': string;
  'user_pop': string;
  'website': string;
}
export const cssExports: CssExports;
export default cssExports;
