// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'brands': string;
  'container': string;
  'desc': string;
  'qrcode': string;
  'qrcode_wrap': string;
  'title': string;
  'tk_desc': string;
}
export const cssExports: CssExports;
export default cssExports;
