// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'done': string;
  'head': string;
  'icon': string;
  'item': string;
  'name': string;
  'search_input': string;
  'title': string;
  'token_list': string;
  'total': string;
}
export const cssExports: CssExports;
export default cssExports;
