// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'container': string;
  'desc': string;
  'first': string;
  'first_title': string;
  'left': string;
  'left_inner': string;
  'link': string;
  'main_title': string;
  'right': string;
  'sidebar': string;
  'strong': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
