// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'current_item': string;
  'desc': string;
  'done': string;
  'hd': string;
  'head': string;
  'item': string;
  'items': string;
  'reset': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
