// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abs_item': string;
  'abstract': string;
  'col_1': string;
  'col_2': string;
  'col_3': string;
  'col_4': string;
  'col_5': string;
  'content': string;
  'green': string;
  'head': string;
  'head_inner': string;
  'head_right': string;
  'icon': string;
  'item_fullname': string;
  'item_symbol': string;
  'label': string;
  'list': string;
  'list_hd': string;
  'list_item': string;
  'red': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
