// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bd': string;
  'box': string;
  'btn': string;
  'container': string;
  'd': string;
  'data': string;
  'datas': string;
  'desc': string;
  'done_btn': string;
  'finish_desc': string;
  'finish_logo': string;
  'finish_title': string;
  'hd': string;
  'hd_item': string;
  'hd_item_cur': string;
  'icon': string;
  'info_item': string;
  'info_label': string;
  'info_title': string;
  'info_title_swap': string;
  'info_value': string;
  'label': string;
  'left': string;
  'left_inner': string;
  'line': string;
  'link': string;
  'main_title': string;
  'my_pair_info': string;
  'name': string;
  'pair_box': string;
  'pair_left': string;
  'pair_right': string;
  'price': string;
  'right': string;
  'sidebar': string;
  'small_title': string;
  'strong': string;
  'subtitle': string;
  'switch_icon': string;
  'title': string;
  'v_item': string;
  'values': string;
  'view_detail': string;
}
export const cssExports: CssExports;
export default cssExports;
