// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app_hide': string;
  'app_start_btn': string;
  'app_title': string;
  'box': string;
  'close': string;
  'col_1': string;
  'col_2': string;
  'col_3': string;
  'container': string;
  'content': string;
  'delete': string;
  'desc': string;
  'icon': string;
  'item_title': string;
  'left': string;
  'left_inner': string;
  'link': string;
  'list': string;
  'list_hd': string;
  'list_item': string;
  'main_title': string;
  'no_data': string;
  'no_data_title': string;
  'q_col_1': string;
  'q_col_2': string;
  'right': string;
  'sidebar': string;
  'strong': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
